export type FilterData = {
    withPaintings: boolean;
    mostIllustrated: boolean;
    withEnglishTranslation: boolean;
    ethiopianStories: boolean;
    miracleOfMaryStories: boolean;
    lifeOfMaryStories: boolean;
    earliestStories: boolean;
    recentStories: boolean;
    popularStories: boolean;
    uniqueStories: boolean;
    centuryRange: number[];
    originAfrica: boolean;
    originEgypt: boolean;
    originEthiopia: boolean;
    originEurope: boolean;
    originFrance: boolean;
    originSpain: boolean;
    originLevant: boolean;
    originUnknown: boolean;
    manuscriptsWithStoryRange: number[],
    paintingsOfStoryRange: number[],
    languagesGeez: boolean;
    languagesArabic: boolean;
    languagesAmharic: boolean;
    languagesEnglish: boolean;
    languagesFrench: boolean;
    languagesItalian: boolean;
    languagesLatin: boolean;
    substring: string;
}
