export type Instances = {
    manuscript?: string | null,
    canonical_story_id?: string | null,
    recension_id?: string | null,
    canonical_story_title?: string | null,
    folio_start?: string | null,
    scan_start?: string | null,
    column_start?: number | null,
    line_start?: number | null,
    body_of_story_start?: string | null,
    folio_end?: string | null,
    scan_end?: string | null,
    column_end?: number | null,
    line_end?: number | null,
    miracle_number?: number | null,
    date_range_mean?: number | null,
    incipit?: string | null,
    story_paintings?: number | null,
    story_century?: number | null,
}