export type Manuscripts = {
    manuscript_id?: number | null,
    manuscript_name?: string | null,
    manuscript_full_name?: string | null,
    language?: string | null,
    date_range_start?: number | null,
    date_range_end?: number | null,
    date_note?: string | null,
    provenance?: string | null,
    total_stories?:  number | null,
    tm_story_paintings?: string | null,
    total_tm_paintings?: number | null,
    scans_of_manuscript_in_color?: string| null,
    link_to_digital_copy?: string| null,
    total_folios?: number| null,
    total_pages?: number| null,
    total_scans?: number| null,
    columns_per_page?: number| null,
    line_range_per_column?: string| null,
    folio_start_of_the_tm_part?: string| null,
    scan_start_of_the_tm_part?: string| null,
    mss_rebound_in_disorder_or_there_are_breaks_in_the_sequence_of_tm?: string|null,
    duplicate_missing_scans_rebound_in_disorder?: string| null,
    pemm_cataloger_name?: string | null, 
    print_cataloger_name?: string | null, 
    pemm_volunteer_name?: string | null,
    catalog?: string| null,
    

  }
