export type Stories = {
    macomber_id?: string | null,
    macomber_title?: string | null,
    english_translation?: string | null,
    total_paintings?: number | null,
    origin?: string | null,
    non_life_miracle?: boolean | null,
    earliest_attestation?: number | null,
    total_records?: number | null,
    theme?: string | null,
    canonical_incipit?: string | null,
    has_english_translation?: boolean | null,
    appears_in_arabic?: boolean | null,
    story_type?: string | null,
    story_subjects?: string | null,
    story_keywords?: string | null,
    story_incipit?: string | null,
    story_incipit_number?: number | null,
    story_translation_source?: string | null,
    story_pemm_id?: number | null,
    story_hamburg_id?: string | null,
    story_macomber_id?: string | null,
    story_csm_id?: number | null,
    story_poncelet_number?: number | null,
    story_gmp_manuscripts?: string | null,
  }
