import Footer from '../common/footer';
import NavBar from '../common/navbar';
import Head from 'next/head'

interface LayoutProps {
    children: React.ReactNode;
 }

const MainLayout = ({ children }: LayoutProps) => {
  return (
    <>
        <Head>
          <title>Pemmtastic</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar/>
          <main className="h-screen">
            {children}
          </main>
        <Footer/>
    </>
  )
}

export default MainLayout
